services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - reward-net

  auth:
    build: ./auth
    ports:
      - "3001:3001"
    volumes:
      - ./auth:/app
    networks:
      - reward-net
    env_file:
      - ./auth/.env

  event:
    build: ./event
    ports:
      - "3002:3002"
    volumes:
      - ./event:/app
    networks:
      - reward-net
    env_file:
      - ./event/.env

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    volumes:
      - ./gateway:/app
    networks:
      - reward-net
    env_file:
      - ./gateway/.env

networks:
  reward-net:
    driver: bridge